engines:
    eslint:
        enabled: true
        checks:
            wrap-iife:
                - error
                - inside
ratings:
    paths:
        - "src/js/**/*.js"
exclude_paths:
    - "tools/**/*"
