engines:
    eslint:
        enabled: true
        checks:
            wrap-iife:
                - "inside"
            no-extend-native:
                enabled: false
ratings:
    paths:
        - "src/js/**/*.js"
exclude_paths:
    - "tools/**/*"
