engines:
    duplication:
        enabled: true
    config:
        languages:
            - javascript
    eslint:
        enabled: true
        checks:
            wrap-iife: "inside"
            no-extend-native:
                enabled: false
    fixme:
        enabled: true
ratings:
    paths:
        - "src/"
exclude_paths:
    - "tools/"
